MONGO_CLIENT_URL = "mongodb://localhost:27017/"
AUTO_COMPLETE_LENGTH = 2
CHARTS_TAB_NAMES = {"HUAWEI2G_Hourly_tab", "HUAWEI2G_Daily_tab", "HUAWEI4G_Hourly_tab", "HUAWEI4G_Daily_tab",
                    "HUAWEI5G_Hourly_tab", "HUAWEI5G_Daily_tab"}

GSM_DB = "GSM_TEST_DB"
GSM_CELL_NAMES_COL = "GSM_CELL_NAMES"
GSM_SITE_NAMES_COL = "GSM_SITE_NAMES"

LTE_DB = "LTE_TEST_DB"
LTE_CELL_NAMES_COL = "LTE_CELL_NAMES"
LTE_ENODEB_NAMES_COL = "LTE_ENODEB_NAMES"

NR_DB = "NR_TEST_DB"
NR_CELL_NAMES_COL = "NR_CELL_NAMES"
NR_GNODEB_NAMES_COL = "NR_GNODEB_NAMES"

EP_DB_NAME = "EP"
LTE_EP_COL_NAME = "LTE_EP"
CLUTSER_COL_NAME = "CLUSTERS"
ISDP_COL_NAME="ISDP"